### ISSUE TITLE
Update the first part of the README

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#12]
## Description 📹

**Update the first part of the README (API) to include more detailed instructions on how to run the project. Use the README from [Inspi](https://github.com/lfglabs-dev/api.starknet.quest) as a reference for structure and content.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
	Update the README file. Specific tasks:
   - [ ] Add a detailed **Setup** section to explain prerequisites, dependencies, and environment setup.
   - [ ] Include commands for installing dependencies, setting up  config files, and running the project locally.
   - [ ] Ensure the structure is aligned with the reference README, adapting to this repository's specific context.

3. **Run Tests and Commit Changes**:  
   Verify that the updated instructions work and commit with a clear message:
   
```bash
   git commit -m "Fix: Update README with detailed API running instructions"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by vestor-dev** [comment]
Hey @Marchand-Nicolas can I hop on this issue?

**Comment by Kingsuite** [comment]
@Marchand-Nicolas can i make this my first contribution the the starkquest eco system

**Comment by CollinsC1O** [comment]
Hi @Marchand-Nicolas I will love to take on this and get it done, kindly assign please

**Comment by SudiptaPaul-31** [comment]
May I be assigned to this?

**Comment by Emmanex01** [comment]
I'd be happy to do this.

**Comment by Benjtalkshow** [comment]
Can I jump on this task?

**Comment by Michaelkingsdev** [comment]
Can I take this issue?

**Comment by 0xdevcollins** [comment]
Let me handle this issue!

**Comment by Aditya-040** [comment]
Can I handle this task?

**Comment by mimisavage** [comment]
I'd love to work on this!

**Comment by Kritto** [comment]
I will update the first part of the README to include comprehensive instructions on how to run the project, ensuring the setup process is clear and straightforward. 

I’ll draw from the 'Inspi' README as a reference to structure the content, providing specific details about prerequisites, dependencies, and environment setup. The updated instructions will cover necessary commands for installing dependencies, configuring files, and running the project locally.

Assign me this task so I can update the README with detailed API running instructions, ensuring smooth setup and clear guidance for future developers. I would love to tackle this!

**Comment by mayasimi** [comment]
Can I be assigned to this?

**Comment by NueloSE** [comment]
Mind if I take this issue?

**Comment by emmz3230** [comment]
hi 
I am a front-end web developer and technical writer.

write the more detailed readme 
I will first check the older readme first and read to know where their is going to be change using the ispi as a reference.
i will ask question where need and when done will send pr and make neccesary changes where needed

**Comment by hossamanany** [comment]
Can I work on this, please?

**Comment by suhas-sensei** [comment]
I’d like to resolve this. hoping to get assigned.

**Comment by 3th-Enjay** [comment]
Can I attempt this issue?
