### ISSUE TITLE
Replace some println by our logger

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#14]
## Description 📹

**Replace all occurrences of `println` with `logger.info(...)` in the files `sale_actions/src/main.rs` and `api_endpoint/src/main.rs`. Ensure the changes conform to the logging conventions established in the project.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

```bash
git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
   Update the code to replace `println` with `logger.info(...)`. Ensure you test all scenarios where the logger is invoked.

   ### Code Snippet (Example)
   - [ ] Replace:
     ```rust
     println!("Message to log");
     ```
     With:
     ```rust
     logger.info("Message to log");
     ```
   - [ ] Update `sale_actions/src/main.rs`.
   - [ ] Update `api_endpoint/src/main.rs`.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

```bash
git commit -m "Fix: Replace println with logger.info in main.rs files"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by petersdt** [comment]
@Marchand-Nicolas can i handle this. kindly assign me please

**Comment by Kingsuite** [comment]
@Marchand-Nicolas can i be assigned to work on this task

**Comment by CollinsC1O** [comment]
Hi @Marchand-Nicolas I will love to work on this issue

**Comment by vestor-dev** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by NueloSE** [comment]
@Marchand-Nicolas  kindly assign me

**Comment by Emmanex01** [comment]
May I pick this up?

**Comment by Benjtalkshow** [comment]
Can I try solving this issue?

**Comment by Michaelkingsdev** [comment]
I'd like to take this issue.

**Comment by 0xdevcollins** [comment]
Can I attempt this issue?

**Comment by Kritto** [comment]
I will replace all occurrences of 'println' with 'logger.info(...)' in the 'sale_actions/src/main.rs' and 'api_endpoint/src/main.rs' files, ensuring that the changes follow the established logging conventions. 

This will enhance logging consistency across the project. After implementing the changes, I will run tests to confirm that everything functions as expected before committing the updates.

Assign me, so I can start working on the specified adjustments immediately.

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by NueloSE** [comment]
Could I be assigned to this?

**Comment by suhas-sensei** [comment]
Could I be assigned to this? i will do the requested changes.

**Comment by 847850277** [comment]
May I be assigned to this?
