### ISSUE TITLE
Add test for to_hex

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#15]
## Description 📹

**Add tests for the `to_hex` functions located in `api_endpoint/src/utils.rs` and `sale_actions/src/utils.rs`. These tests should ensure the function correctly converts various inputs into their hexadecimal string representations.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
   Add unit tests for the `to_hex` functions in the respective files. Ensure all edge cases and normal cases are handled.

```rust
    #[test]
    fn test_to_hex_valid_input() {
        let input = ...;
        let expected = "...";
        assert_eq!(to_hex(&input), expected);
    }
```

- [ ] Add tests for `to_hex` in `api_endpoint/src/utils.rs`.  
- [ ] Add tests for `to_hex` in `sale_actions/src/utils.rs`.  
- [ ] Cover edge cases like empty input, etc.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Fix: Add tests for to_hex functions in utils.rs"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by martinvibes** [comment]
Hey @Marchand-Nicolas i'm a blockchain dev and i'd be happy to work on this issue please kindly assign

**Comment by CollinsC1O** [comment]
Hi @Marchand-Nicolas I'm a front-end and a blockchain developer. I will love to work on this

**Comment by vestor-dev** [comment]
hey @Marchand-Nicolas Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by Emmanex01** [comment]
I’m interested in this one.

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by Birdmannn** [comment]
Hey @Marchand-Nicolas I would like to embark on this issue. I am a web2/web3 developer with experience with cairo and rust, they are more or like the same
thing. I would like to contribute to this repository.

***Steps***
1. Create a test function in the corresponding file, and carry out all possible tests on the `to_hex` function to clear out current and future bugs
2. Follow out he steps required when making a pull request afterwards
3. This exercise will be carried out in 2 days maximum, with constant check-ins

**Comment by 0xdevcollins** [comment]
I'd like to take this issue.

**Comment by mimisavage** [comment]
Can I jump on this task?

**Comment by petersdt** [comment]
May I handle this issue?

am a frontend dev. with some level of experience writing test for functions implemented in js rust python and even cairo.

kindly assign me the above task.

ETA <= 48hrs

**Comment by mayasimi** [comment]
Can I tackle this one?

**Comment by NueloSE** [comment]
May I take care of this?

**Comment by hossamanany** [comment]
Can I take this from here?

**Comment by suhas-sensei** [comment]
I'd be happy to do this. i have the required experience in rust and cairo and i can manage writing test cases for the said functions. expect a draft pr in 24hrs.

**Comment by 847850277** [comment]
I’d love to work on this task.

**Comment by ooochoche** [comment]
I've gone through the description and the requirements and I can add test for the required function within the required duration

**Comment by suhas-sensei** [comment]
thank you for the assignment.

**Comment by Marchand-Nicolas** [comment]
Done here https://github.com/lfglabs-dev/api.sales.starknet.id/pull/18
