### ISSUE TITLE
Improve indexer part in the README

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#21]
## Description 📹

**Add a mention in the README that a token for the indexer can be generated for free on Apibara at: [https://www.apibara.com/](https://www.apibara.com/)**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
```bash
   git checkout -b fix-[issue-number]
```

2. **Implement Changes**:  
   Update the README file by adding a note in the appropriate section about generating a free token for the indexer from Apibara.
   - [ ] Locate the section in the README file where instructions for the indexer or prerequisites are mentioned.
   - [ ] Add a note with the following content (or similar):

   > **Note**: A free token for the indexer can be generated on Apibara. Visit [[Apibara's website](https://www.apibara.com/)](https://www.apibara.com/) for more details.

   - [ ] Verify that the formatting of the new note aligns with the existing README style.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
```bash
   git commit -m "Docs: Add note about generating free token on Apibara"
```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing Close #[issue_id].
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by malikrohail** [comment]
can i fix?

**Comment by aurlic** [comment]
Hey I would love to be able to contribute on this project and I think this could be a good first issue to discover the project ! Thanks in advance

**Comment by Shalomnze** [comment]
I'd love to work on this!

**Comment by Crosstons** [comment]
I can work on this

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by zanastas** [comment]
I’d love to work on this task.

**Comment by Yunusabdul38** [comment]
Could I take a shot at this?
i would like to work on this issue  as my first contribution to this project

**Comment by SudiptaPaul-31** [comment]
Can I take this issue?

My approach:

First go the readme file of the project and make the changes in the indexer part
And then making a pr  

ETA-1day
