### ISSUE TITLE
Replace `.expect` calls in `api_endpoint/src/endpoints/newsletter_subscribe.rs`

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#22]
## Description 📹

Replace `.expect` calls in `api_endpoint/src/endpoints/newsletter_subscribe.rs` with `logger.severe(msg)` so that error messages are logged to Watchtower instead of panicking the application.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:
   - [ ] Replace `.expect` calls with `logger.severe(msg)`.
   - [ ] Use the logger instance from `AppState` to log severe errors.
   - [ ] Update the `find_one` error handling:
     ```rust
     let result = collection
         .find_one(filter, None)
         .await
         .unwrap_or_else(|err| {
             state.logger.severe(format!("Failed to execute find_one: {}", err));
             return get_error("Internal server error".to_string());
         });
     ```
   - [ ] Replace the `to_bson` serialization `.expect` with logger-based error handling:
     ```rust
     let bson_doc = match mongodb::bson::to_bson(&AddNewsletterRecord {
         email: query.email,
         address: query.address,
         source: "newsletter_subscription".to_string(),
     }) {
         Ok(bson) => bson,
         Err(err) => {
             state.logger.severe(format!("Failed to serialize to BSON: {}", err));
             return get_error("Internal server error".to_string());
         }
     };
     ```
   - [ ] Handle other `.expect` calls similarly using `logger.severe`.

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Replace .expect calls with logger.severe for Watchtower logging"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by SergioArrighi** [comment]
Can I attempt this issue?

**Comment by mimisavage** [comment]
I'd love to give this a go.

**Comment by 847850277** [comment]
I’m interested in this one.Can it be assigned to me

**Comment by MrRoudyk** [comment]
May I take care of this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
  please /assign  this issue .
Thank You

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on rust projects. I will replace remove every .expect and take error message in it and replace with logger.sever(error message).
