### ISSUE TITLE
Replace `.expect` calls in `api_endpoint/src/endpoints/mail_subscribe.rs` 

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#23]
## Description 📹

Replace `.expect` calls in `api_endpoint/src/endpoints/mail_subscribe.rs` with `logger.severe(msg)` so that error messages are logged to Watchtower instead of panicking the application.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:
   - [ ] Replace `.expect` calls with `logger.severe(msg)`.
   - [ ] Use the logger instance from `AppState` to log severe errors.
   - [ ] Update the `to_bson` serialization `.expect`:
     ```rust
     let bson_doc = match mongodb::bson::to_bson(&MailSubscribeDoc {
         tx_hash: query.tx_hash,
         group,
     }) {
         Ok(bson) => bson,
         Err(err) => {
             state.logger.severe(format!("Failed to serialize to BSON: {}", err));
             return get_error("Internal server error".to_string());
         }
     };
     ```
   - [ ] Ensure the BSON creation and insertion error handling uses `logger.severe`:
     ```rust
     if let mongodb::bson::Bson::Document(document) = bson_doc {
         match emails_collection.insert_one(document, None).await {
             Ok(_) => (),
             Err(err) => {
                 state.logger.severe(format!("Failed to insert document: {}", err));
                 return get_error("Internal server error".to_string());
             }
         }
     } else {
         state.logger.severe("Failed to create BSON document".to_string());
         return get_error("Internal server error".to_string());
     }
     ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Replace .expect calls with logger.severe for Watchtower logging in mail_subscribe.rs"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by aurlic** [comment]
Hey I would love to get to work on this issue and improve my skills. Thanks in advance !

**Comment by SergioArrighi** [comment]
Hello team!
I would love to find projects to collaborate with to legitimate my non-professional skillset. I am a senior developer with 18+ years of experience as Java backend developer. Last 4/5 years upskilling as Web3 full stack developer (Typescript/Rust/Solidity).
My portfolio http://sarrighi.info.
Regards

**Comment by jaykayudo** [comment]
GM @Marchand-Nicolas Can i work on this as soon as ODHACK11 starts?

- I will follow the guidelines listed above to fork and create a branch . The branch will be created based on this issue number.
- I will replace the `.expect` calls in `api_endpoint/src/endpoints/mail_subscribe.rs` with `logger.severe(msg)`
- I will use the logger instance to log severe errors and update the `to_bson` serialization to log the error via the logger instance
- I will ensure the BSON creation and insertion error handling uses `logger.severe(msg)`
- I will commit with a clear commit and i will test to ensure no breaking change occurred
- I will make a PR for review before the end of 2 business days and the PR will reference this issue via the `Close #[issue_id]` description

**Comment by mimisavage** [comment]
I'd like to take this issue.

**Comment by Yunusabdul38** [comment]
Can I start working on this?
will be glad to work on this as my first contribution to this project
i will apply the necessary change and make sure it work as expected

**Comment by MrRoudyk** [comment]
I’d love to work on this task.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
please /assign  this issue .
Thank You

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on rust projects. I will replace remove every .expect and take error message in it and replace with logger.sever(error message).
