### ISSUE TITLE
Replace `.expect` calls in `api_endpoint/src/endpoints/add_metadata.rs`

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.sales.starknet.id#24]
## Description 📹

Replace `.expect` calls in `api_endpoint/src/endpoints/add_metadata.rs` with `logger.severe(msg)` so that error messages are logged to Watchtower instead of panicking the application.

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:

   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:
   - [ ] Replace `.expect` calls with `logger.severe(msg)`.
   - [ ] Use the logger instance from `AppState` to log severe errors.
   - [ ] Update the `to_bson` serialization `.expect`:
     ```rust
     let bson_doc = match mongodb::bson::to_bson(&query) {
         Ok(bson) => bson,
         Err(err) => {
             state.logger.severe(format!("Failed to serialize to BSON: {}", err));
             return get_error("Internal server error".to_string());
         }
     };
     ```
   - [ ] Ensure BSON creation and insertion error handling uses `logger.severe`:
     ```rust
     if let mongodb::bson::Bson::Document(document) = bson_doc {
         match metadata_collection.insert_one(document, None).await {
             Ok(_) => (),
             Err(err) => {
                 state.logger.severe(format!("Failed to insert document: {}", err));
                 return get_error("Internal server error".to_string());
             }
         }
     } else {
         state.logger.severe("Failed to create BSON document".to_string());
         return get_error("Internal server error".to_string());
     }
     ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:

   ```bash
   git commit -m "Fix: Replace .expect calls with logger.severe for Watchtower logging in add_metadata.rs"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

**Comment by aurlic** [comment]
Hey I am a student at school 42 and I'm learning Cairo and Rust and I would be ahppy to give a shot at this issue. I tink it could be a good amtch for me as I would further develop my skills and get to know the project. Thanks in advance !

**Comment by Crosstons** [comment]
May I take this issue on?

**Comment by codebestia** [comment]
@Marchand-Nicolas May i handle this issue?

I will follow the proposed actions step by step which involved creating a branch with the proposed branch title, replacing the `.expect` with `logger.severe(msg)`, using the logger instance from the `Appstate` to log severe errors, Updating the `to_bson` serialization to use the logger,  ensuring BSON creation and insertion handles error with the logger, writing a clear and concise commit message and making a PR within 3 business days.

I ensure that this task will be completed soon.

**Comment by mimisavage** [comment]
I can handle this task, kindly assign,

**Comment by zanastas** [comment]
May I be assigned to this?

**Comment by Yunusabdul38** [comment]
Can I start working on this?
i will apply the necessary change and make sure it work as expected

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by RajeshRk18** [comment]
Can I take up this issue? I have experience working on rust projects. I will replace remove every .expect and take error message in it and replace with logger.sever(error message).
